SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60
FONT = 'comicsans'

ASSETS_PATH = 'Assets'
IMAGES_PATH = ASSETS_PATH + '\Images'
SKELETON_IMAGE = 'skeleton.png'
GOBLIN_IMAGE = 'goblin.png'
ORC_IMAGE = 'orc.png'
SPIDER_IMAGE = 'spider.png'
DOOR_IMAGE = 'door.png'
BOMB_IMAGE = 'bomb.png'
FOOD_IMAGE = 'food.png'
SCROLL_IMAGE = 'scroll.png'
TREASURE_IMAGE = 'treasure.png'
BOW_IMAGE = 'bow.png'
AXE_IMAGE = 'axe.png'

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREY = (100, 100, 100)
ORANGE = (207, 142, 109)
GREEN = (120, 240, 120)
STATS_COLOURS = {'Health' : (25, 130, 30), 'Damage' : (180, 0 ,0), 'Armour' : (50, 50, 180), 'Luck' : (190, 190, 40)}

BORDER_ACTION_OFFSET_X_PERCENT = 0.6
BORDER_STATS_OFFSET_Y = 100
BORDER_WIDTH = 5

ACTION_LOG_OFFSET_X = 25
ACTION_LOG_OFFSET_Y = 15
ACTION_LOG_TEXT_SIZE = 15
ACTION_LOG_GAP = 15

STATS_OFFSET_FROM_BORDER_X = 25
STATS_OFFSET_FROM_BORDER_Y = 25
STAT_VALUE_OFFSET = 10
STATS_GAP = 25
STAT_TEXT_SIZE = 20

BASE_STATS = {'Health' : 10, 'Damage' : 10, 'Armour' : 2, 'Luck' : 5}

START_BUTTON_WIDTH = 170
START_BUTTON_HEIGHT = 55
START_BUTTON_TEXT_SIZE = 45

BUTTON_OUTLINE_THICKNESS = 3
BUTTON_WIDTH = 100
BUTTON_HEIGHT = 50
BUTTON_TEXT_SIZE = 45

START_BUTTON_TEXT = 'Start'
ATTACK_BUTTON_TEXT = 'Attack'
ITEM_BUTTON_TEXT = 'Use Item'
PARRY_BUTTON_TEXT = 'Parry'
EVADE_BUTTON_TEXT = 'Evade'

DOOR_WIDTH = 330
DOOR_HEIGHT = 380
ITEM_WIDTH = 100
ITEM_HEIGHT = 100

GAME_START_DELAY = 0.5
REMOVE_ENEMY_DELAY = 1

MAX_NUMBER_OF_ROOMS = 5
ITEM_PROBABILITY = 0.25
ROOMS_CONTENTS_PROBABILITIES = {'Food' : 0.2, 'Enemy' : 0.6, 'Artifact' : 0.1, 'Item' : 0.1}
ENEMIES_PROBABILITIES = {'Skeleton' : 0.45, 'Goblin' : 0.25, 'Orc' : 0.15, 'Spider' : 0.15}

GREETING_MESSAGE = 'Welcome to the dungeon!'
ROOM_ENTERED_MESSAGE = 'Room entered'

SKELETON_STATS = {'Health' : 3, 'Damage' : 2}
GOBLIN_STATS = {'Health' : 3, 'Damage' : 2}
ORC_STATS = {'Health' : 3, 'Damage' : 2}
SPIDER_STATS = {'Health' : 3, 'Damage' : 2}